// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server_urls.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The URLs provided by the go-daemon server.
type ServerUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiBaseUrl    *string                `protobuf:"bytes,1,opt,name=api_base_url,json=apiBaseUrl" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUrls) Reset() {
	*x = ServerUrls{}
	mi := &file_server_urls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUrls) ProtoMessage() {}

func (x *ServerUrls) ProtoReflect() protoreflect.Message {
	mi := &file_server_urls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUrls.ProtoReflect.Descriptor instead.
func (*ServerUrls) Descriptor() ([]byte, []int) {
	return file_server_urls_proto_rawDescGZIP(), []int{0}
}

func (x *ServerUrls) GetApiBaseUrl() string {
	if x != nil && x.ApiBaseUrl != nil {
		return *x.ApiBaseUrl
	}
	return ""
}

var File_server_urls_proto protoreflect.FileDescriptor

const file_server_urls_proto_rawDesc = "" +
	"\n" +
	"\x11server_urls.proto\".\n" +
	"\n" +
	"ServerUrls\x12 \n" +
	"\fapi_base_url\x18\x01 \x01(\tR\n" +
	"apiBaseUrlB%Z#github.com/mwopitz/go-daemon/daemonb\beditionsp\xe8\a"

var (
	file_server_urls_proto_rawDescOnce sync.Once
	file_server_urls_proto_rawDescData []byte
)

func file_server_urls_proto_rawDescGZIP() []byte {
	file_server_urls_proto_rawDescOnce.Do(func() {
		file_server_urls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_urls_proto_rawDesc), len(file_server_urls_proto_rawDesc)))
	})
	return file_server_urls_proto_rawDescData
}

var file_server_urls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_urls_proto_goTypes = []any{
	(*ServerUrls)(nil), // 0: ServerUrls
}
var file_server_urls_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_urls_proto_init() }
func file_server_urls_proto_init() {
	if File_server_urls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_urls_proto_rawDesc), len(file_server_urls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_urls_proto_goTypes,
		DependencyIndexes: file_server_urls_proto_depIdxs,
		MessageInfos:      file_server_urls_proto_msgTypes,
	}.Build()
	File_server_urls_proto = out.File
	file_server_urls_proto_goTypes = nil
	file_server_urls_proto_depIdxs = nil
}
