// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server_process.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The status of the go-daemon server process.
type ServerProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *uint32                `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerProcess) Reset() {
	*x = ServerProcess{}
	mi := &file_server_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProcess) ProtoMessage() {}

func (x *ServerProcess) ProtoReflect() protoreflect.Message {
	mi := &file_server_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProcess.ProtoReflect.Descriptor instead.
func (*ServerProcess) Descriptor() ([]byte, []int) {
	return file_server_process_proto_rawDescGZIP(), []int{0}
}

func (x *ServerProcess) GetPid() uint32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

var File_server_process_proto protoreflect.FileDescriptor

const file_server_process_proto_rawDesc = "" +
	"\n" +
	"\x14server_process.proto\"!\n" +
	"\rServerProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pidB%Z#github.com/mwopitz/go-daemon/daemonb\beditionsp\xe8\a"

var (
	file_server_process_proto_rawDescOnce sync.Once
	file_server_process_proto_rawDescData []byte
)

func file_server_process_proto_rawDescGZIP() []byte {
	file_server_process_proto_rawDescOnce.Do(func() {
		file_server_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_process_proto_rawDesc), len(file_server_process_proto_rawDesc)))
	})
	return file_server_process_proto_rawDescData
}

var file_server_process_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_process_proto_goTypes = []any{
	(*ServerProcess)(nil), // 0: ServerProcess
}
var file_server_process_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_process_proto_init() }
func file_server_process_proto_init() {
	if File_server_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_process_proto_rawDesc), len(file_server_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_process_proto_goTypes,
		DependencyIndexes: file_server_process_proto_depIdxs,
		MessageInfos:      file_server_process_proto_msgTypes,
	}.Build()
	File_server_process_proto = out.File
	file_server_process_proto_goTypes = nil
	file_server_process_proto_depIdxs = nil
}
