// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: status_request.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options for querying the status of the daemon server.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_status_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_status_request_proto_rawDescGZIP(), []int{0}
}

var File_status_request_proto protoreflect.FileDescriptor

const file_status_request_proto_rawDesc = "" +
	"\n" +
	"\x14status_request.proto\"\x0f\n" +
	"\rStatusRequestB%Z#github.com/mwopitz/go-daemon/daemonb\beditionsp\xe8\a"

var (
	file_status_request_proto_rawDescOnce sync.Once
	file_status_request_proto_rawDescData []byte
)

func file_status_request_proto_rawDescGZIP() []byte {
	file_status_request_proto_rawDescOnce.Do(func() {
		file_status_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_request_proto_rawDesc), len(file_status_request_proto_rawDesc)))
	})
	return file_status_request_proto_rawDescData
}

var file_status_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_status_request_proto_goTypes = []any{
	(*StatusRequest)(nil), // 0: StatusRequest
}
var file_status_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_status_request_proto_init() }
func file_status_request_proto_init() {
	if File_status_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_request_proto_rawDesc), len(file_status_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_request_proto_goTypes,
		DependencyIndexes: file_status_request_proto_depIdxs,
		MessageInfos:      file_status_request_proto_msgTypes,
	}.Build()
	File_status_request_proto = out.File
	file_status_request_proto_goTypes = nil
	file_status_request_proto_depIdxs = nil
}
