// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: todo_daemon.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TodoDaemon_GetStatus_FullMethodName = "/mwopitz.todo.v1.TodoDaemon/GetStatus"
)

// TodoDaemonClient is the client API for TodoDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC interface of the To-do Daemon.
type TodoDaemonClient interface {
	// Queries the status of the To-do Daemon.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*Status, error)
}

type todoDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoDaemonClient(cc grpc.ClientConnInterface) TodoDaemonClient {
	return &todoDaemonClient{cc}
}

func (c *todoDaemonClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, TodoDaemon_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoDaemonServer is the server API for TodoDaemon service.
// All implementations must embed UnimplementedTodoDaemonServer
// for forward compatibility.
//
// The gRPC interface of the To-do Daemon.
type TodoDaemonServer interface {
	// Queries the status of the To-do Daemon.
	GetStatus(context.Context, *GetStatusRequest) (*Status, error)
	mustEmbedUnimplementedTodoDaemonServer()
}

// UnimplementedTodoDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTodoDaemonServer struct{}

func (UnimplementedTodoDaemonServer) GetStatus(context.Context, *GetStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTodoDaemonServer) mustEmbedUnimplementedTodoDaemonServer() {}
func (UnimplementedTodoDaemonServer) testEmbeddedByValue()                    {}

// UnsafeTodoDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoDaemonServer will
// result in compilation errors.
type UnsafeTodoDaemonServer interface {
	mustEmbedUnimplementedTodoDaemonServer()
}

func RegisterTodoDaemonServer(s grpc.ServiceRegistrar, srv TodoDaemonServer) {
	// If the following call pancis, it indicates UnimplementedTodoDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TodoDaemon_ServiceDesc, srv)
}

func _TodoDaemon_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDaemonServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDaemon_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDaemonServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoDaemon_ServiceDesc is the grpc.ServiceDesc for TodoDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mwopitz.todo.v1.TodoDaemon",
	HandlerType: (*TodoDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _TodoDaemon_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo_daemon.proto",
}
